package com.webtest.demo;

import com.webtest.core.BaseTest;
import org.openqa.selenium.Alert;
import org.openqa.selenium.By;
import org.testng.Assert;
import org.testng.annotations.Test;

public class BookStoreTest extends BaseTest {
    String url="http://localhost:8080/page/login";
    String url1="http://localhost:8080/admin";

    public void login() throws InterruptedException {
        this.driver.get(url);
        driver.findElement(By.name("username")).sendKeys("admin");
        driver.findElement(By.name("password")).sendKeys("123");
        driver.findElement(By.xpath("//input[@type='submit']")).click();
        this.driver.get(url1);
    }
    public void loginFront() throws InterruptedException {
        this.driver.get(url);
        Thread.sleep(2000);
        driver.findElement(By.name("username")).sendKeys("admin");
        driver.findElement(By.name("password")).sendKeys("123");
        driver.findElement(By.xpath("//input[@type='submit']")).click();
        Thread.sleep(2000);
    }

    //后台管理-云店铺
    @Test
    public void test1() throws InterruptedException {
        login();
        webtest.enterFrame(0);
        webtest.enterFrame(0);
        webtest.click("link=云店铺");
        Thread.sleep(2000);
        Assert.assertTrue(webtest.isElementPresent("link=店铺列表"));
    }
    @Test
    public void test2() throws InterruptedException {
        login();
        webtest.enterFrame(0);
        webtest.enterFrame(0);
        webtest.click("link=云店铺");
        Thread.sleep(2000);
        webtest.click("link=云店铺");
        Thread.sleep(2000);
        Assert.assertFalse(webtest.isElementPresent("link=店铺列表"));
    }
    @Test
    public void test3() throws InterruptedException {
        login();
        webtest.enterFrame(0);
        webtest.enterFrame(0);
        webtest.click("link=云店铺");
        Thread.sleep(1000);
        webtest.click("link=店铺列表");
        Thread.sleep(1000);
        webtest.leaveFrame();
        webtest.enterFrame(0);
        webtest.enterFrame(1);
        Assert.assertTrue(webtest.isElementPresent("xpath=//th[contains(text(),'商店名称')]"));
    }
    @Test
    public void test4() throws InterruptedException {
        login();
        webtest.enterFrame(0);
        webtest.enterFrame(0);
        webtest.click("link=云店铺");
        Thread.sleep(1000);
        webtest.click("link=添加店铺");
        Thread.sleep(1000);
        webtest.leaveFrame();
        webtest.enterFrame(0);
        webtest.enterFrame(1);
        Assert.assertTrue(webtest.isElementPresent("xpath=//*[@id=\"storeForm\"]/div[1]/label"));
    }
    //云店铺-店铺列表
    @Test
    public void test5() throws InterruptedException {
        login();
        webtest.enterFrame(0);
        webtest.enterFrame(0);
        webtest.click("link=云店铺");
        Thread.sleep(1000);
        webtest.click("link=店铺列表");
        Thread.sleep(1000);
        webtest.leaveFrame();
        webtest.enterFrame(0);
        webtest.enterFrame(1);
        webtest.click("xpath=/html/body/div/table/tbody/tr[1]/td[9]/button[2]");
        Assert.assertEquals("真的要删除？",webtest.getAlertTest());
    }
    @Test
    public void test6() throws InterruptedException {
        login();
        webtest.enterFrame(0);
        webtest.enterFrame(0);
        webtest.click("link=云店铺");
        Thread.sleep(1000);
        webtest.click("link=店铺列表");
        Thread.sleep(1000);
        webtest.leaveFrame();
        webtest.enterFrame(0);
        webtest.enterFrame(1);
        webtest.click("xpath=/html/body/div/table/tbody/tr[1]/td[9]/button[2]");
        webtest.alertDismiss();
        Thread.sleep(1000);
        Assert.assertTrue(webtest.isElementPresent("xpath=//th[contains(text(),'商店名称')]"));
    }
    @Test
    public void test7() throws InterruptedException {
        login();
        webtest.enterFrame(0);
        webtest.enterFrame(0);
        webtest.click("link=云店铺");
        Thread.sleep(1000);
        webtest.click("link=店铺列表");
        Thread.sleep(1000);
        webtest.leaveFrame();
        webtest.enterFrame(0);
        webtest.enterFrame(1);
        webtest.click("xpath=/html/body/div/table/tbody/tr[1]/td[9]/button[2]");
        webtest.alertAccept();
        Thread.sleep(1000);
        Assert.assertFalse(webtest.isElementPresent("xpath=//td[contains(text(),'商店1号')]"));
    }
    @Test
    public void test8() throws InterruptedException {
        login();
        webtest.enterFrame(0);
        webtest.enterFrame(0);
        webtest.click("link=云店铺");
        Thread.sleep(1000);
        webtest.click("link=店铺列表");
        Thread.sleep(1000);
        webtest.leaveFrame();
        webtest.enterFrame(0);
        webtest.enterFrame(1);
        webtest.click("xpath=/html/body/div/table/tbody/tr[1]/td[9]/button[1]");
        Thread.sleep(1000);
        Assert.assertTrue(webtest.isElementPresent("xpath=//h2[contains(text(),'编辑店铺信息')]"));
    }
    @Test
    public void test9() throws InterruptedException {
        login();
        webtest.enterFrame(0);
        webtest.enterFrame(0);
        webtest.click("link=云店铺");
        Thread.sleep(1000);
        webtest.click("link=店铺列表");
        Thread.sleep(1000);
        webtest.leaveFrame();
        webtest.enterFrame(0);
        webtest.enterFrame(1);
        webtest.click("xpath=/html/body/div/table/tbody/tr[1]/td[9]/button[1]");
        Thread.sleep(1000);
        webtest.typeAndClear("id=storeName","123456");
        Thread.sleep(3000);
        Assert.assertFalse(webtest.isDisplayed("id=storeName-error"));
    }
    @Test
    public void test10() throws InterruptedException {
        login();
        webtest.enterFrame(0);
        webtest.enterFrame(0);
        webtest.click("link=云店铺");
        Thread.sleep(1000);
        webtest.click("link=店铺列表");
        Thread.sleep(1000);
        webtest.leaveFrame();
        webtest.enterFrame(0);
        webtest.enterFrame(1);
        webtest.click("xpath=/html/body/div/table/tbody/tr[1]/td[9]/button[1]");
        Thread.sleep(1000);
        webtest.typeAndClear("id=storeName","abcde");
        Assert.assertFalse(webtest.isDisplayed("id=storeName-error"));
    }
    @Test
    public void test11() throws InterruptedException {
        login();
        webtest.enterFrame(0);
        webtest.enterFrame(0);
        webtest.click("link=云店铺");
        Thread.sleep(1000);
        webtest.click("link=店铺列表");
        Thread.sleep(1000);
        webtest.leaveFrame();
        webtest.enterFrame(0);
        webtest.enterFrame(1);
        webtest.click("xpath=/html/body/div/table/tbody/tr[1]/td[9]/button[1]");
        Thread.sleep(1000);
        webtest.typeAndClear("id=storeName","~!@#$%^");
        Assert.assertFalse(webtest.isDisplayed("id=storeName-error"));
    }
    @Test
    public void test12() throws InterruptedException {
        login();
        webtest.enterFrame(0);
        webtest.enterFrame(0);
        webtest.click("link=云店铺");
        Thread.sleep(1000);
        webtest.click("link=店铺列表");
        Thread.sleep(1000);
        webtest.leaveFrame();
        webtest.enterFrame(0);
        webtest.enterFrame(1);
        webtest.click("xpath=/html/body/div/table/tbody/tr[1]/td[9]/button[1]");
        Thread.sleep(1000);
        webtest.typeAndClear("id=storePhoneNum","1581462356");
        Assert.assertTrue(webtest.isDisplayed("id=storePhoneNum-error"));
    }
    @Test
    public void test13() throws InterruptedException {
        login();
        webtest.enterFrame(0);
        webtest.enterFrame(0);
        webtest.click("link=云店铺");
        Thread.sleep(1000);
        webtest.click("link=店铺列表");
        Thread.sleep(1000);
        webtest.leaveFrame();
        webtest.enterFrame(0);
        webtest.enterFrame(1);
        webtest.click("xpath=/html/body/div/table/tbody/tr[1]/td[9]/button[1]");
        Thread.sleep(1000);
        webtest.typeAndClear("id=storePhoneNum","19831124917");
        Thread.sleep(3000);
        Assert.assertFalse(webtest.isDisplayed("id=storePhoneNum-error"));
    }
    @Test
    public void test14() throws InterruptedException {
        login();
        webtest.enterFrame(0);
        webtest.enterFrame(0);
        webtest.click("link=云店铺");
        Thread.sleep(1000);
        webtest.click("link=店铺列表");
        Thread.sleep(1000);
        webtest.leaveFrame();
        webtest.enterFrame(0);
        webtest.enterFrame(1);
        webtest.click("xpath=/html/body/div/table/tbody/tr[1]/td[9]/button[1]");
        Thread.sleep(1000);
        webtest.typeAndClear("id=storePhoneNum","13911122222");
        Thread.sleep(3000);
        Assert.assertFalse(webtest.isDisplayed("id=storePhoneNum-error"));
    }
    @Test
    public void test15() throws InterruptedException {
        login();
        webtest.enterFrame(0);
        webtest.enterFrame(0);
        webtest.click("link=云店铺");
        Thread.sleep(1000);
        webtest.click("link=店铺列表");
        Thread.sleep(1000);
        webtest.leaveFrame();
        webtest.enterFrame(0);
        webtest.enterFrame(1);
        webtest.click("xpath=/html/body/div/table/tbody/tr[1]/td[9]/button[1]");
        Thread.sleep(1000);
        webtest.typeAndClear("id=storePhoneNum","abcdefghijk");
        Thread.sleep(3000);
        Assert.assertTrue(webtest.isDisplayed("id=storePhoneNum-error"));
    }
    @Test
    public void test16() throws InterruptedException {
        login();
        webtest.enterFrame(0);
        webtest.enterFrame(0);
        webtest.click("link=云店铺");
        Thread.sleep(1000);
        webtest.click("link=店铺列表");
        Thread.sleep(1000);
        webtest.leaveFrame();
        webtest.enterFrame(0);
        webtest.enterFrame(1);
        webtest.click("xpath=/html/body/div/table/tbody/tr[1]/td[9]/button[1]");
        Thread.sleep(1000);
        webtest.typeAndClear("id=storePhoneNum","~!@#$%^&*()");
        Thread.sleep(3000);
        Assert.assertTrue(webtest.isDisplayed("id=storePhoneNum-error"));
    }
    @Test
    public void test17() throws InterruptedException {
        login();
        webtest.enterFrame(0);
        webtest.enterFrame(0);
        webtest.click("link=云店铺");
        Thread.sleep(1000);
        webtest.click("link=店铺列表");
        Thread.sleep(1000);
        webtest.leaveFrame();
        webtest.enterFrame(0);
        webtest.enterFrame(1);
        webtest.click("xpath=/html/body/div/table/tbody/tr[1]/td[9]/button[1]");
        Thread.sleep(1000);
        webtest.typeAndClear("id=storeTelephone","123");
        Thread.sleep(3000);
        Assert.assertTrue(webtest.isDisplayed("id=storePhoneNum-error"));
    }
    @Test
    public void test18() throws InterruptedException {
        login();
        webtest.enterFrame(0);
        webtest.enterFrame(0);
        webtest.click("link=云店铺");
        Thread.sleep(1000);
        webtest.click("link=店铺列表");
        Thread.sleep(1000);
        webtest.leaveFrame();
        webtest.enterFrame(0);
        webtest.enterFrame(1);
        webtest.click("xpath=/html/body/div/table/tbody/tr[1]/td[9]/button[1]");
        Thread.sleep(1000);
        webtest.typeAndClear("id=storeTelephone","abcde");
        Thread.sleep(3000);
        Assert.assertTrue(webtest.isDisplayed("id=storeTelephone-error"));
    }
    @Test
    public void test19() throws InterruptedException {
        login();
        webtest.enterFrame(0);
        webtest.enterFrame(0);
        webtest.click("link=云店铺");
        Thread.sleep(1000);
        webtest.click("link=店铺列表");
        Thread.sleep(1000);
        webtest.leaveFrame();
        webtest.enterFrame(0);
        webtest.enterFrame(1);
        webtest.click("xpath=/html/body/div/table/tbody/tr[1]/td[9]/button[1]");
        Thread.sleep(1000);
        webtest.typeAndClear("id=storeTelephone","~!@#$");
        Thread.sleep(3000);
        Assert.assertTrue(webtest.isDisplayed("id=storeTelephone-error"));
    }
    @Test
    public void test20() throws InterruptedException {
        login();
        webtest.enterFrame(0);
        webtest.enterFrame(0);
        webtest.click("link=云店铺");
        Thread.sleep(1000);
        webtest.click("link=店铺列表");
        Thread.sleep(1000);
        webtest.leaveFrame();
        webtest.enterFrame(0);
        webtest.enterFrame(1);
        webtest.click("xpath=/html/body/div/table/tbody/tr[1]/td[9]/button[1]");
        Thread.sleep(1000);
        webtest.typeAndClear("id=storePosition","123456");
        Thread.sleep(3000);
        Assert.assertTrue(webtest.isDisplayed("id=storePosition-error"));
    }
    @Test
    public void test21() throws InterruptedException {
        login();
        webtest.enterFrame(0);
        webtest.enterFrame(0);
        webtest.click("link=云店铺");
        Thread.sleep(1000);
        webtest.click("link=店铺列表");
        Thread.sleep(1000);
        webtest.leaveFrame();
        webtest.enterFrame(0);
        webtest.enterFrame(1);
        webtest.click("xpath=/html/body/div/table/tbody/tr[1]/td[9]/button[1]");
        Thread.sleep(1000);
        webtest.typeAndClear("id=storePosition","abcde");
        Thread.sleep(3000);
        Assert.assertTrue(webtest.isDisplayed("id=storePosition-error"));
    }
    @Test
    public void test22() throws InterruptedException {
        login();
        webtest.enterFrame(0);
        webtest.enterFrame(0);
        webtest.click("link=云店铺");
        Thread.sleep(1000);
        webtest.click("link=店铺列表");
        Thread.sleep(1000);
        webtest.leaveFrame();
        webtest.enterFrame(0);
        webtest.enterFrame(1);
        webtest.click("xpath=/html/body/div/table/tbody/tr[1]/td[9]/button[1]");
        Thread.sleep(1000);
        webtest.typeAndClear("id=storePosition","石家庄");
        Thread.sleep(3000);
        Assert.assertFalse(webtest.isDisplayed("id=storePosition-error"));
    }
    //云店铺-添加店铺
    @Test
    public void test23() throws InterruptedException {
        login();
        webtest.enterFrame(0);
        webtest.enterFrame(0);
        webtest.click("link=云店铺");
        webtest.click("link=添加店铺");
        webtest.leaveFrame();
        webtest.enterFrame(0);
        webtest.enterFrame(1);
        webtest.click("id=storeManagerId");
        webtest.selectByValue("id=storeManagerId","1");
        webtest.type("id=storeName","admin商店");
        webtest.type("id=storePhoneNum","15814516280");
        webtest.type("id=storeTelephone","1234567");
        webtest.type("id=storePosition","深圳");
        Thread.sleep(2000);
        webtest.click("xpath=/html/body/div/form/div[6]/div/button");
        Thread.sleep(2000);
        Assert.assertTrue(webtest.isElementPresent("xpath=//h2[contains(text(),'店铺列表')]"));
    }
    @Test
    public void test24() throws InterruptedException {
        login();
        webtest.enterFrame(0);
        webtest.enterFrame(0);
        webtest.click("link=云店铺");
        Thread.sleep(1000);
        webtest.click("link=添加店铺");
        Thread.sleep(1000);
        webtest.leaveFrame();
        webtest.enterFrame(0);
        webtest.enterFrame(1);
        Thread.sleep(1000);
        webtest.click("xpath=/html/body/div/form/div[6]/div/button");
        Assert.assertTrue(webtest.isElementPresent("xpath=//*[@id=\"storeForm\"]/div[1]/label"));
    }
    @Test
    public void test25() throws InterruptedException {
        login();
        webtest.enterFrame(0);
        webtest.enterFrame(0);
        webtest.click("link=云店铺");
        Thread.sleep(1000);
        webtest.click("link=添加店铺");
        Thread.sleep(1000);
        webtest.leaveFrame();
        webtest.enterFrame(0);
        webtest.enterFrame(1);
        webtest.type("id=storeName","admin商店");
        Thread.sleep(1000);
        Assert.assertTrue(webtest.isDisplayed("id=storeName-error"));
    }
    @Test
    public void test26() throws InterruptedException {
        login();
        webtest.enterFrame(0);
        webtest.enterFrame(0);
        webtest.click("link=云店铺");
        Thread.sleep(1000);
        webtest.click("link=添加店铺");
        Thread.sleep(1000);
        webtest.leaveFrame();
        webtest.enterFrame(0);
        webtest.enterFrame(1);
        webtest.type("id=storeName","123456");
        Thread.sleep(1000);
        Assert.assertFalse(webtest.isDisplayed("id=storeName-error"));
    }
    @Test
    public void test27() throws InterruptedException {
        login();
        webtest.enterFrame(0);
        webtest.enterFrame(0);
        webtest.click("link=云店铺");
        Thread.sleep(1000);
        webtest.click("link=添加店铺");
        Thread.sleep(1000);
        webtest.leaveFrame();
        webtest.enterFrame(0);
        webtest.enterFrame(1);
        webtest.type("id=storeName","~!@#$%^");
        Thread.sleep(1000);
        Assert.assertFalse(webtest.isDisplayed("id=storeName-error"));
    }
    @Test
    public void test28() throws InterruptedException {
        login();
        webtest.enterFrame(0);
        webtest.enterFrame(0);
        webtest.click("link=云店铺");
        Thread.sleep(1000);
        webtest.click("link=添加店铺");
        Thread.sleep(1000);
        webtest.leaveFrame();
        webtest.enterFrame(0);
        webtest.enterFrame(1);
        webtest.type("id=storePhoneNum","1581462356");
        Thread.sleep(3000);
        Assert.assertTrue(webtest.isDisplayed("id=storePhoneNum-error"));
    }
    @Test
    public void test29() throws InterruptedException {
        login();
        webtest.enterFrame(0);
        webtest.enterFrame(0);
        webtest.click("link=云店铺");
        Thread.sleep(1000);
        webtest.click("link=添加店铺");
        Thread.sleep(1000);
        webtest.leaveFrame();
        webtest.enterFrame(0);
        webtest.enterFrame(1);
        webtest.type("id=storePhoneNum","19831124917");
        Thread.sleep(3000);
        Assert.assertFalse(webtest.isDisplayed("id=storePhoneNum-error"));
    }
    @Test
    public void test30() throws InterruptedException {
        login();
        webtest.enterFrame(0);
        webtest.enterFrame(0);
        webtest.click("link=云店铺");
        Thread.sleep(1000);
        webtest.click("link=添加店铺");
        Thread.sleep(1000);
        webtest.leaveFrame();
        webtest.enterFrame(0);
        webtest.enterFrame(1);
        webtest.type("id=storePhoneNum","13911122222");
        Thread.sleep(3000);
        Assert.assertFalse(webtest.isDisplayed("id=storePhoneNum-error"));
    }
    @Test
    public void test31() throws InterruptedException {
        login();
        webtest.enterFrame(0);
        webtest.enterFrame(0);
        webtest.click("link=云店铺");
        Thread.sleep(1000);
        webtest.click("link=添加店铺");
        Thread.sleep(1000);
        webtest.leaveFrame();
        webtest.enterFrame(0);
        webtest.enterFrame(1);
        webtest.type("id=storePhoneNum","abcdefghijk");
        Thread.sleep(3000);
        Assert.assertTrue(webtest.isDisplayed("id=storePhoneNum-error"));
    }
    @Test
    public void test32() throws InterruptedException {
        login();
        webtest.enterFrame(0);
        webtest.enterFrame(0);
        webtest.click("link=云店铺");
        Thread.sleep(1000);
        webtest.click("link=添加店铺");
        Thread.sleep(1000);
        webtest.leaveFrame();
        webtest.enterFrame(0);
        webtest.enterFrame(1);
        webtest.type("id=storePhoneNum","~!@#$%^&*()");
        Thread.sleep(3000);
        Assert.assertTrue(webtest.isDisplayed("id=storePhoneNum-error"));
    }
    @Test
    public void test33() throws InterruptedException {
        login();
        webtest.enterFrame(0);
        webtest.enterFrame(0);
        webtest.click("link=云店铺");
        Thread.sleep(1000);
        webtest.click("link=添加店铺");
        Thread.sleep(1000);
        webtest.leaveFrame();
        webtest.enterFrame(0);
        webtest.enterFrame(1);
        webtest.type("id=storeTelephone","");
        Thread.sleep(3000);
        Assert.assertFalse(webtest.isDisplayed("id=storeTelephone-error"));
    }
    @Test
    public void test34() throws InterruptedException {
        login();
        webtest.enterFrame(0);
        webtest.enterFrame(0);
        webtest.click("link=云店铺");
        Thread.sleep(1000);
        webtest.click("link=添加店铺");
        Thread.sleep(1000);
        webtest.leaveFrame();
        webtest.enterFrame(0);
        webtest.enterFrame(1);
        webtest.type("id=storeTelephone","123");
        Thread.sleep(3000);
        Assert.assertTrue(webtest.isDisplayed("id=storeTelephone-error"));
    }
    @Test
    public void test35() throws InterruptedException {
        login();
        webtest.enterFrame(0);
        webtest.enterFrame(0);
        webtest.click("link=云店铺");
        Thread.sleep(1000);
        webtest.click("link=添加店铺");
        Thread.sleep(1000);
        webtest.leaveFrame();
        webtest.enterFrame(0);
        webtest.enterFrame(1);
        webtest.type("id=storePhoneNum","abcde");
        Thread.sleep(3000);
        Assert.assertTrue(webtest.isDisplayed("id=storeTelephone-error"));
    }
    @Test
    public void test36() throws InterruptedException {
        login();
        webtest.enterFrame(0);
        webtest.enterFrame(0);
        webtest.click("link=云店铺");
        Thread.sleep(1000);
        webtest.click("link=添加店铺");
        Thread.sleep(1000);
        webtest.leaveFrame();
        webtest.enterFrame(0);
        webtest.enterFrame(1);
        webtest.type("id=storePosition","123456");
        Thread.sleep(3000);
        Assert.assertTrue(webtest.isDisplayed("id=storePosition-error"));
    }
    @Test
    public void test37() throws InterruptedException {
        login();
        webtest.enterFrame(0);
        webtest.enterFrame(0);
        webtest.click("link=云店铺");
        Thread.sleep(1000);
        webtest.click("link=添加店铺");
        Thread.sleep(1000);
        webtest.leaveFrame();
        webtest.enterFrame(0);
        webtest.enterFrame(1);
        webtest.type("id=storePosition","abcde");
        Thread.sleep(3000);
        Assert.assertTrue(webtest.isDisplayed("id=storePosition-error"));
    }
    //后台管理-前往
    @Test
    public void test38() throws InterruptedException {
        login();
        webtest.enterFrame(0);
        webtest.enterFrame(0);
        webtest.click("link=前往");
        Thread.sleep(2000);
        Assert.assertTrue(webtest.isElementPresent("link=前台首页"));
    }
    @Test
    public void test39() throws InterruptedException {
        login();
        webtest.enterFrame(0);
        webtest.enterFrame(0);
        webtest.click("link=前往");
        Thread.sleep(2000);
        webtest.click("link=前往");
        Thread.sleep(2000);
        Assert.assertFalse(webtest.isElementPresent("link=前台首页"));
    }
    @Test
    public void test40() throws InterruptedException {
        login();
        webtest.enterFrame(0);
        webtest.enterFrame(0);
        webtest.click("link=前往");
        Thread.sleep(1000);
        webtest.click("link=前台首页");
        Thread.sleep(1000);
        webtest.leaveFrame();
        Assert.assertTrue(webtest.isElementPresent("id=keywords"));
    }
    @Test
    public void test41() throws InterruptedException {
        login();
        webtest.enterFrame(0);
        webtest.enterFrame(0);
        webtest.click("link=前往");
        Thread.sleep(1000);
        webtest.click("link=后台首页");
        Thread.sleep(1000);
        webtest.leaveFrame();
        webtest.enterFrame(0);
        webtest.enterFrame(1);
        Assert.assertTrue(webtest.isElementPresent("xpath=//h1[contains(text(),'dd图书后台管理系统')]"));
    }
    @Test
    public void test42() throws InterruptedException {
        login();
        webtest.enterFrame(0);
        webtest.enterFrame(0);
        webtest.click("link=前往");
        Thread.sleep(1000);
        webtest.click("link=注销");
        Thread.sleep(1000);
        webtest.leaveFrame();
        Assert.assertTrue(webtest.isElementPresent("id=register"));
    }
    //前台首页顶端
    @Test
    public void test43() throws InterruptedException {
        loginFront();
        webtest.click("xpath=/html/body/div[1]/div/ul/li[5]/a");
        Thread.sleep(2000);
        Assert.assertTrue(webtest.isElementPresent("id=register"));
    }
    @Test
    public void test44() throws InterruptedException {
        loginFront();
        webtest.click("xpath=//a[contains(text(),'admin')]");
        Thread.sleep(2000);
        Assert.assertTrue(webtest.isElementPresent("xpath=//p[contains(text(),'admin')]"));
    }
    @Test
    public void test45() throws InterruptedException {
        loginFront();
        webtest.click("xpath=//a[contains(text(),'免费注册')]");
        Thread.sleep(2000);
        Assert.assertTrue(webtest.isElementPresent("xpath=//span[contains(text(),'新用户注册/企业用户注册')]"));
    }
    @Test
    public void test46() throws InterruptedException {
        loginFront();
        webtest.click("xpath=/html/body/div[1]/div/ul/li[1]/div/button");
        Thread.sleep(2000);
        Assert.assertTrue(webtest.isElementPresent("xpath=//a[contains(text(),'个人信息')]"));
    }
    @Test
    public void test47() throws InterruptedException {
        loginFront();
        webtest.click("xpath=/html/body/div[1]/div/ul/li[1]/div/button");
        Thread.sleep(2000);
        webtest.click("xpath=/html/body/div[1]/div/ul/li[1]/div/button");
        Assert.assertFalse(webtest.isDisplayed("xpath=//a[contains(text(),'个人信息')]"));
    }
    @Test
    public void test48() throws InterruptedException {
        loginFront();
        webtest.click("xpath=/html/body/div[1]/div/ul/li[1]/div/button");
        Thread.sleep(2000);
        webtest.click("xpath=//a[contains(text(),'个人信息')]");
        Assert.assertTrue(webtest.isElementPresent("id=userInfoForm"));
    }
    @Test
    public void test49() throws InterruptedException {
        loginFront();
        webtest.click("xpath=/html/body/div[1]/div/ul/li[1]/div/button");
        Thread.sleep(2000);
        webtest.click("xpath=//a[contains(text(),'后台管理')]");
        Assert.assertTrue(webtest.isElementPresent("link=云店铺"));
    }
    @Test
    public void test50() throws InterruptedException {
        loginFront();
        webtest.click("xpath=/html/body/div[1]/div/ul/li[1]/div/button");
        Thread.sleep(2000);
        webtest.click("xpath=//a[contains(text(),'注销')]");
        Assert.assertTrue(webtest.isElementPresent("id=register"));
    }
}
